-- tests/notifications/init_spec.lua
local notifications = require("notifications")

describe("notifications", function()
    it("exports level_names table", function()
        assert.are.equal("INFO", notifications.level_names[vim.log.levels.INFO])
        assert.are.equal("ERROR", notifications.level_names[vim.log.levels.ERROR])
        assert.are.equal("OFF", notifications.level_names[5])
    end)

    it("notify() accepts valid levels and does not throw (currently a stub)", function()
        assert.has_no.errors(function()
            notifications.notify("hello")
            notifications.notify("warn", vim.log.levels.WARN)
            notifications.notify("with opts", vim.log.levels.INFO, { title = "hi" })
        end)
    end)

    it("notify() rejects invalid levels", function()
        local ok, err = pcall(function()
            notifications.notify("bad", 99)
        end)
        assert.is_false(ok)
        assert.matches("Invalid log level", err)
    end)
end)
